# Generated by Django 4.2.4 on 2023-08-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paisent',
            name='phoneno',
        ),
    ]
