# Generated by Django 4.2.4 on 2023-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0002_remove_paisent_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='paisent',
            name='mobileno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
