# Generated by Django 4.2.4 on 2023-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_paisent_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='paisent',
            name='adress',
            field=models.CharField(null=True),
        ),
    ]
