# Generated by Django 4.2.4 on 2023-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_paisent_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paisent',
            name='adress',
        ),
        migrations.AddField(
            model_name='paisent',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
