# Generated by Django 4.2.4 on 2023-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0005_remove_paisent_adress_paisent_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paisent',
            name='gmail',
        ),
        migrations.AddField(
            model_name='paisent',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
